version: '3.7'

services:
  transcoder:
    image: voodfy/transcoder:latest
    volumes:
      - ./logs:/app/logs
      - ./conf:/app/conf
      - /tmp/:/tmp/
    depends_on:
      - redis
      - ipfs
    stdin_open: true
    tty: true

  redis:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - 'redisdata:/data'

  ipfs:
    container_name: 'ipfs'
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "4003:4003" # ipfs ws - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - /tmp/:/tmp/

  influxdb:
    image: appcelerator/influxdb:latest
    ports:
      - 8086:8086
    environment:
      - PRE_CREATE_DB="metrics"

  powergate:
    image: textile/powergate:latest
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
    depends_on:
      - ipfs
      - lotus
    environment:
      - POWD_DEVNET=true
      - POWD_LOTUSHOST=/dns4/lotus/tcp/7777
      - POWD_IPFSAPIADDR=/dns4/ipfs/tcp/5001
    restart: unless-stopped

  lotus:
    image: textile/lotus-devnet:v0.4.0
    ports:
      - 7777:7777
    environment:
      - TEXLOTUSDEVNET_SPEED=1500
      - TEXLOTUSDEVNET_BIGSECTORS=${BIGSECTORS}
      - TEXLOTUSDEVNET_IPFSADDR=/dns4/ipfs/tcp/5001

volumes:
  redisdata:
