
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.14.2
    environment:
    - TEST_RESULTS: /tmp/test-results
    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS
    - run:
        command: |
          sudo apt-get update -y && sudo apt-get install -y ssh rsync
    - run:
        environment: null
        GIN_MODE: test
        command: |
          trap "go test ./... > ${TEST_RESULTS}/go-test-report.xml" EXIT
          make test | tee ${TEST_RESULTS}/go-test.out
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results

    - deploy:
        name: Deploy Master to videostreaming transcoder
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
          go build -o main .

          rsync -avzh -e "ssh -o StrictHostKeyChecking=no" main devops@34.237.124.65:/home/devops/apps/voodfy/transcoder/src/

          ssh -o StrictHostKeyChecking=no devops@34.237.124.65 << EOF
          cd /home/devops/apps/voodfy/transcoder/src/ && mv main transcoder && cd /home/devops/
          sh deploy_voodfy_transcoder.sh
          EOF

          fi
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - /feature-.*/
            - /feature.*/
